# Generated by Django 3.2 on 2021-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya_nomi', models.CharField(max_length=50)),
                ('rusumi', models.CharField(max_length=50)),
                ('xotirasi', models.IntegerField()),
                ('tezkor_xotirasi', models.IntegerField()),
                ('narxi', models.IntegerField()),
            ],
        ),
    ]
